export const httpFlags = {
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_BODY: 'INVALID_BODY',
  INVALID_PARAM: 'INVALID_PARAM',
  INVALID_HEADERS: 'INVALID_HEADERS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_UNAUTHORIZED: 'USER_UNAUTHORIZED',
  USER_BLOCKED: 'USER_BLOCKED',
  EMAIL_ALREADY_EXIST: 'EMAIL_ALREADY_EXIST',
  EMAIL_OR_PASSWORD_INVALID: 'EMAIL_OR_PASSWORD_INVALID'
}
