name: CI to Docker Hub

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          cp .env.example .env
          npm install
          npm run dependency:local
          sleep 5
          npm run test

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - run: cp .env.example .env
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_IQBAL }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          logout: true

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_IQBAL }}/crud-api:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: 'rizkiiqbal36@gmail.com'
        env:
          HD_APP_ENV: ${{ secrets.APP_ENV }}
          HD_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          HD_ENCRYPT_JWT_SECRET: ${{ secrets.ENCRYPT_JWT_SECRET }}
          HD_JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          HD_MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
          HD_MONGO_DB_DB_NAME: ${{ secrets.MONGO_DB_DB_NAME }}
          HD_MONGO_DB_USER: ${{ secrets.MONGO_DB_USER }}
          HD_MONGO_DB_PASS: ${{ secrets.MONGO_DB_PASS }}
          HD_MONGO_DB_AUTH_SOURCE: ${{ secrets.MONGO_DB_AUTH_SOURCE }}
